// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSa2ZcA3giNZojJmvcmLuGtS5UC0fYbLs',
    appId: '1:250602997068:web:d4574675e9ea4daeed3be9',
    messagingSenderId: '250602997068',
    projectId: 'coffee-shop345',
    authDomain: 'coffee-shop345.firebaseapp.com',
    storageBucket: 'coffee-shop345.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZhjAJ0B5-w5lsw_zcmwzlrZ2rsJCU6gM',
    appId: '1:250602997068:ios:e4e238f840971fa8ed3be9',
    messagingSenderId: '250602997068',
    projectId: 'coffee-shop345',
    storageBucket: 'coffee-shop345.firebasestorage.app',
    iosBundleId: 'com.example.layoutsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSa2ZcA3giNZojJmvcmLuGtS5UC0fYbLs',
    appId: '1:250602997068:web:2957802eac9e47eded3be9',
    messagingSenderId: '250602997068',
    projectId: 'coffee-shop345',
    authDomain: 'coffee-shop345.firebaseapp.com',
    storageBucket: 'coffee-shop345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZhjAJ0B5-w5lsw_zcmwzlrZ2rsJCU6gM',
    appId: '1:250602997068:ios:e4e238f840971fa8ed3be9',
    messagingSenderId: '250602997068',
    projectId: 'coffee-shop345',
    storageBucket: 'coffee-shop345.firebasestorage.app',
    iosBundleId: 'com.example.layoutsFlutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgX0C_s7g1c1E7bVm1HGmelu5-UpTCvxc',
    appId: '1:250602997068:android:abaf44d2480a1504ed3be9',
    messagingSenderId: '250602997068',
    projectId: 'coffee-shop345',
    storageBucket: 'coffee-shop345.firebasestorage.app',
  );

}